//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_Recruitment
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnitReqTable
    {
        public int RequestId { get; set; }
        public int BId { get; set; }
        public Nullable<int> JavaDevReq { get; set; }
        public Nullable<int> DotNetDevReq { get; set; }
        public Nullable<int> BAReq { get; set; }
    
        public virtual BusinessUnitTable BusinessUnitTable { get; set; }
    }
}
